routes/web.php
<?php

use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CrudController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\MeasurementUnitController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductDataController;
use App\Http\Controllers\ProductLedgerController;
use App\Http\Controllers\ProductPurchaseController;
use App\Http\Controllers\StorageController;
use App\Http\Controllers\StorageTypeController;
use App\Http\Controllers\SubmissionController;
use App\Http\Controllers\SubmissionStatusController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TemplateController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('dashboard', DashboardController::class)->name('dashboard');
Route::resource('crud', CrudController::class);

Route::resource('item', ItemController::class);
Route::resource('brand', BrandController::class);
Route::resource('storage', StorageController::class);
Route::resource('storage-type', StorageTypeController::class);
Route::resource('category', CategoryController::class);
Route::resource('supplier', SupplierController::class);
Route::resource('submission-status', SubmissionStatusController::class);
Route::resource('measurement-unit', MeasurementUnitController::class);
Route::resource('product', ProductController::class);
Route::resource('product-purchase', ProductPurchaseController::class);
Route::resource('product-ledger', ProductLedgerController::class);
Route::resource('product-data', ProductDataController::class);
Route::resource('submission', SubmissionController::class);

// Template route
Route::group(['prefix' => 'template', 'as' => 'template.'], function () {
    Route::get('{file}.html', TemplateController::class)->name('dashboard');
});

app/Models/Submission.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Submission extends Model
{
    use HasFactory;

    protected $fillable = [
        'product_id',
        'submission_status_id',
        'qty',
        'requested_by',
        'validated_at',
        'validated_by',
        'checked_at',
        'checked_by',
        'approved_at',
        'approved_by',
        'status_code',
        'created_by',
        'updated_by',
    ];

    public function submission_status()
    {
        return $this->belongsTo(SubmissionStatus::class, 'submission_status_id', 'id');
    }

    public function product()
    {
        return $this->belongsTo(Product::class, 'product_id', 'id');
    }
}

app/Http/Controllers/SubmissionController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\SubmissionRequest;
use App\Models\Submission;
use Illuminate\Support\Facades\DB;

class SubmissionController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $models = Submission::all();
        $data['models'] = $models;

        return view('submission.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('submission.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(SubmissionRequest $request)
    {
        $data = $request->validated();

        try {
            DB::beginTransaction();

            $data['validated_by'] = '950724102025';

            $submission = Submission::create($data);

            DB::commit();
            session()->flash('success', 'Submission has been added.');

            return redirect()->back();
        } catch (\Exception $e) {
            DB::rollback();
            session()->flash('error', $e->getMessage());

            return redirect()->back()->withInput();
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(Submission $submission)
    {
        $data['submission'] = $submission;

        return view('submission.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Submission $submission)
    {
        $data['submission'] = $submission;

        return view('submission.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(SubmissionRequest $request, Submission $submission)
    {
        $data = $request->validated();

        try {
            DB::beginTransaction();

            $data['validated_by'] = '112233445566';

            $submission->update($data);

            DB::commit();
            session()->flash('success', 'Submission has been updated.');

            // return redirect()->back();
            return redirect()->route('submission.index');
        } catch (\Exception $e) {
            DB::rollback();
            session()->flash('error', $e->getMessage());

            return redirect()->back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Submission $submission)
    {
        try {
            DB::beginTransaction();

            $submission->delete();

            DB::commit();
            session()->flash('success', 'Submission has been deleted.');

            return redirect()->route('submission.index');
        } catch (\Exception $e) {
            DB::rollback();
            session()->flash('error', $e->getMessage());

            return redirect()->back()->withInput();
        }
    }
}

resources/views/submission/create.blade.php
<x-layout :title="'Create Dummy CRUD'">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('submission.store') }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="product_id">Product Id</label>
                                <input type="text" value="" id="product_id" name="product_id" class="form-control" placeholder="Product">
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="submission_status_id">Submission Status</label>
                                <input type="text" value="" id="submission_status_id" name="submission_status_id" class="form-control" placeholder="Submission Status">
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="qty">Quantity</label>
                                <input type="number" value="" id="qty" name="qty" class="form-control" placeholder="Quantity">
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="requested_by">Requested By</label>
                                <input type="text" value="" id="requested_by" name="requested_by" class="form-control" placeholder="Requested By">
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="validated_at">Validated At</label>
                                <input type="text" value="" id="validated_at" name="validated_at" class="form-control" placeholder="Validated At">
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="validated_by">Validated By</label>
                                <input type="text" value="" id="validated_by" name="validated_by" class="form-control" placeholder="Validated By">
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="status_code">Status Code</label>
                                <input type="text" value="" id="status_code" name="status_code" class="form-control" placeholder="Status Code">
                            </div>
                        </div>

                        <button class="btn btn-primary" type="submit">
                            <i class="ri-add-box-line me-1 fs-16 lh-1"></i> Create
                        </button>
                        <a href="{{ route('submission.index') }}" class="btn btn-secondary">
                            <i class="ri-arrow-go-back-line me-1 fs-16 lh-1"></i> Back
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

</x-layout>

resources/views/submission/edit.blade.php
<x-layout :title="'Edit Dummy CRUD'">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('submission.update', $submission) }}" method="POST">
                        @csrf
                        @method('PATCH')
                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="product_id">Product Id</label>
                                <input type="text" value="{{ $submission->product_id }}" id="product_id" name="product_id" class="form-control" placeholder="Product">
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="submission_status_id">Submission Status</label>
                                <input type="text" value="{{ $submission->submission_status_id }}" id="submission_status_id" name="submission_status_id" class="form-control" placeholder="Submission Status">
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="qty">Quantity</label>
                                <input type="number" value="{{ $submission->qty }}" id="qty" name="qty" class="form-control" placeholder="Quantity">
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="requested_by">Requested By</label>
                                <input type="text" value="{{ $submission->requested_by }}" id="requested_by" name="requested_by" class="form-control" placeholder="Requested By">
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="validated_at">Validated At</label>
                                <input type="text" value="{{ $submission->validated_at }}" id="validated_at" name="validated_at" class="form-control" placeholder="Validated At">
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="validated_by">Validated By</label>
                                <input type="text" value="{{ $submission->validated_by }}" id="validated_by" name="validated_by" class="form-control" placeholder="Validated By">
                            </div>
                        </div>

                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="status_code">Status Code</label>
                                <input type="text" value="{{ $submission->status_code }}" id="status_code" name="status_code" class="form-control" placeholder="Status Code">
                            </div>
                        </div>
                        <button class="btn btn-primary" type="submit">
                            <i class="ri-save-line me-1 fs-16 lh-1"></i> Save
                        </button>
                        <a href="{{ route('submission.index') }}" class="btn btn-secondary">
                            <i class="ri-arrow-go-back-line me-1 fs-16 lh-1"></i> Back
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

</x-layout>

resources/views/submission/index.blade.php
@push('before-styles')
    <!-- Datatables css -->
    <link href="{{ asset('velonicadmin/vendor/datatables.net-bs5/css/dataTables.bootstrap5.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-fixedcolumns-bs5/css/fixedColumns.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-fixedheader-bs5/css/fixedHeader.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-buttons-bs5/css/buttons.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-select-bs5/css/select.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
@endpush
@push('before-scripts')
    <!-- Datatables js -->
    <script src="{{ asset('velonicadmin/vendor/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-bs5/js/dataTables.bootstrap5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-fixedcolumns-bs5/js/fixedColumns.bootstrap5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons-bs5/js/buttons.bootstrap5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-select/js/dataTables.select.min.js') }}"></script>
    <script>
        $('.datatable').DataTable({
            keys: true,
            "language": {
                "paginate": {
                    "previous": "<i class='ri-arrow-left-s-line'>",
                    "next": "<i class='ri-arrow-right-s-line'>"
                }
            },
            "drawCallback": function () {
                $('.dataTables_paginate > .pagination').addClass('pagination-rounded');
            }
        });
    </script>
@endpush

<x-layout :title="'Browse Submission CRUD'">

    <div class="row">
        <div class="col-12">
            <a href="{{ route('submission.create') }}" class="btn btn-primary mb-3">
                <i class="ri-save-line me-1 fs-16 lh-1"></i> New
            </a>
            <div class="card">
                <div class="card-body">
                    <table class="datatable table table-striped dt-responsive nowrap w-100">
                        <thead>
                            <tr>
                                <th>Quantity</th>
                                <th>Requested By</th>
                                <th>Created At</th>
                                <th>Validated By</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($models ?? [] as $model)
                            <tr>
                                <td>
                                    {{ $model->qty }}
                                </td>
                                <td>
                                    {{ $model->requested_by }}
                                </td>
                                <td>
                                    {{ $model->created_at->format('Y-m-d') }}
                                </td>
                                <td>
                                    {{ $model->validated_by }}
                                </td>
                                <td>
                                    <a href="{{ route('submission.edit', $model) }}" class="btn btn-primary">
                                        <i class="ri-pencil-line me-1 fs-16 lh-1"></i> Edit
                                    </a>
                                    <a href="{{ route('submission.show', $model) }}" class="btn btn-secondary">
                                        <i class="ri-search-eye-line me-1 fs-16 lh-1"></i> View
                                    </a>
                                    <form action="{{ route('submission.destroy', $model)}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">
                                            <i class="ri-search-eye-line me-1 fs-16 lh-1"></i> Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</x-layout>

resources/views/submission/show.blade.php
<x-layout :title="'Show Dummy CRUD'">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-condensed mb-0 border-top">
                        <tbody>
                            <tr>
                                <th scope="row">Label Text</th>
                                <td>
                                    Input Value
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">Label Text</th>
                                <td>
                                    Input Value
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <a href="{{ route('crud.index') }}" class="btn btn-secondary mt-2">
                        <i class="ri-arrow-go-back-line me-1 fs-16 lh-1"></i> Back
                    </a>
                </div>
            </div>
        </div>
    </div>

</x-layout>