routes/web.php
<?php

use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CrudController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\MeasurementUnitController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductDataController;
use App\Http\Controllers\ProductLedgerController;
use App\Http\Controllers\ProductPurchaseController;
use App\Http\Controllers\StorageController;
use App\Http\Controllers\StorageTypeController;
use App\Http\Controllers\SubmissionController;
use App\Http\Controllers\SubmissionStatusController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TemplateController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('dashboard', DashboardController::class)->name('dashboard');
Route::resource('crud', CrudController::class);

Route::resource('item', ItemController::class);
Route::resource('brand', BrandController::class);
Route::resource('storage', StorageController::class);
Route::resource('storage-type', StorageTypeController::class);
Route::resource('category', CategoryController::class);
Route::resource('supplier', SupplierController::class);
Route::resource('submission-status', SubmissionStatusController::class);
Route::resource('measurement-unit', MeasurementUnitController::class);
Route::resource('product', ProductController::class);
Route::resource('product-purchase', ProductPurchaseController::class);
Route::resource('product-ledger', ProductLedgerController::class);
Route::resource('product-data', ProductDataController::class);
Route::resource('submission', SubmissionController::class);

// Template route
Route::group(['prefix' => 'template', 'as' => 'template.'], function () {
    Route::get('{file}.html', TemplateController::class)->name('dashboard');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $table = 'products';

    protected $fillable = ['product_data_id', 'storage_type_id', 'storage_id', 'measurement_unit_id'];

    public function product_datas()
    {
        return $this->belongsToMany(ProductData::class);
    }

    public function storageType()
    {
        return $this->belongsTo(storageType::class);
    }

    public function storage()
    {
        return $this->belongsTo(Storage::class);
    }

    public function measurement_unit()
    {
        return $this->belongsTo(MeasurementUnit::class);
    }

    public static function listData()
    {
        $data = self::join('product_data', 'product_data.id', 'product_data_id')
            ->join('master_storage_types', 'master_storage_types.id', 'storage_type_id')
            ->join('master_storages', 'master_storages.id', 'storage_id')
            ->join('master_measurement_units', 'master_measurement_units.id', 'measurement_unit_id')
            ->select('products.id', 'product_data_id', 'products.storage_type_id', 'products.storage_id', 'measurement_unit_id', 'master_storage_types.name AS storageTypeName', 'master_storages.name AS storageName', 'master_measurement_units.name AS measureName', 'products.created_at AS created_at');

        return $data;
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductRequest;
use App\Models\MeasurementUnit;
use App\Models\Product;
use App\Models\ProductData;
use App\Models\Storage;
use App\Models\StorageType;
use DB;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $products = Product::listData()->get();

        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $productDatas = ProductData::list()->get();
        $storageTypes = StorageType::list()->get();
        $storages = Storage::list()->get();
        $measurementUnits = MeasurementUnit::list()->get();

        return view('product.create', compact('productDatas', 'storageTypes', 'storages', 'measurementUnits'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(ProductRequest $request)
    {
        $data = $request->validated();

        try {
            DB::beginTransaction();

            Product::create($data);

            DB::commit();
            session()->flash('success', 'Product has been added.');

            return redirect()->route('product.index');
        } catch (\Exception $e) {
            DB::rollback();
            session()->flash('error', $e->getMessage());

            return redirect()->back()->withInput();
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(Product $product)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Product $product)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(ProductRequest $request, Product $product)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Product $product)
    {
        //
    }
}

resources/views/product/create.blade.php
<x-layout :title="'Create Product'">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('product.store') }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="FullName">Product Data</label>
                                <select name="product_data_id" id="product_data_id" class="form-control">
                                    <option value="">--Sila Pilih--</option>
                                    @foreach ($productDatas as $pd)
                                    <option value="{{$pd->id}}">{{$pd->brand.' - '.$pd->item}}</option>   
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="FullName">Storage Type</label>
                                <select name="storage_type_id" id="storage_type_id" class="form-control">
                                    <option value="">--Sila Pilih--</option>
                                    @foreach ($storageTypes as $st)
                                    <option value="{{$st->id}}">{{$st->name}}</option>   
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="FullName">Storage</label>
                                <select name="storage_id" id="storage_id" class="form-control">
                                    <option value="">--Sila Pilih--</option>
                                    @foreach ($storages as $st)
                                    <option value="{{$st->id}}">{{$st->name}}</option>   
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="FullName">Measurement Unit</label>
                                <select name="measurement_unit_id" id="measurement_unit_id" class="form-control">
                                    <option value="">--Sila Pilih--</option>
                                    @foreach ($measurementUnits as $st)
                                    <option value="{{$st->id}}">{{$st->name}}</option>   
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="FullName">Status</label>
                                <select name="status_code" id="status_code" class="form-control">
                                    <option value="1">AKTIF</option>
                                    <option value="0">ARKIB</option>
                                </select>
                            </div>
                        </div>
                        <button class="btn btn-primary" type="submit">
                            <i class="ri-add-box-line me-1 fs-16 lh-1"></i> Create
                        </button>
                        <a href="{{ route('crud.index') }}" class="btn btn-secondary">
                            <i class="ri-arrow-go-back-line me-1 fs-16 lh-1"></i> Back
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

</x-layout>

resources/views/product/edit.blade.php
<x-layout :title="'Edit Dummy CRUD'">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('product.update',$product) }}" method="POST">
                        @csrf
                        @method('PATCH')
                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="FullName">Label Text</label>
                                <input type="text" value="" id="name" name="name" class="form-control" placeholder="Input Placeholder">
                            </div>
                        </div>
                        <button class="btn btn-primary" type="submit">
                            <i class="ri-save-line me-1 fs-16 lh-1"></i> Save
                        </button>
                        <a href="{{ route('crud.index') }}" class="btn btn-secondary">
                            <i class="ri-arrow-go-back-line me-1 fs-16 lh-1"></i> Back
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

</x-layout>

resources/views/product/index.blade.php
@push('before-styles')
    <!-- Datatables css -->
    <link href="{{ asset('velonicadmin/vendor/datatables.net-bs5/css/dataTables.bootstrap5.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-fixedcolumns-bs5/css/fixedColumns.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-fixedheader-bs5/css/fixedHeader.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-buttons-bs5/css/buttons.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-select-bs5/css/select.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
@endpush
@push('before-scripts')
    <!-- Datatables js -->
    <script src="{{ asset('velonicadmin/vendor/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-bs5/js/dataTables.bootstrap5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-fixedcolumns-bs5/js/fixedColumns.bootstrap5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons-bs5/js/buttons.bootstrap5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-select/js/dataTables.select.min.js') }}"></script>
    <script>
        $('.datatable').DataTable({
            keys: true,
            "language": {
                "paginate": {
                    "previous": "<i class='ri-arrow-left-s-line'>",
                    "next": "<i class='ri-arrow-right-s-line'>"
                }
            },
            "drawCallback": function () {
                $('.dataTables_paginate > .pagination').addClass('pagination-rounded');
            }
        });
    </script>
@endpush

<x-layout :title="'Browse Products'">

    <div class="row">
        <div class="col-12">
            <a href="{{ route('product.create') }}" class="btn btn-primary mb-3">
                <i class="ri-save-line me-1 fs-16 lh-1"></i> New
            </a>
            <div class="card">
                <div class="card-body">
                    <table class="datatable table table-striped dt-responsive nowrap w-100">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Product Data Id</th>
                                <th>Storage Type</th>
                                <th>Storage Name</th>
                                <th>Measurement</th>
                                <th>Created At</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($products ?? [] as $product)
                            <tr>
                                <td>
                                    {{ $product->id }}
                                </td>
                                <td>
                                    {{ $product->product_data_id }}
                                </td>
                                <td>
                                    {{ $product->storageType->name }}
                                </td>
                                <td>
                                    {{ $product->storage->name }}
                                </td>
                                <td>
                                    {{ $product->measurement_unit->name ?? "" }}
                                </td>
                                <td>
                                    {{ $product->created_at->format('Y-m-d') }}
                                </td>
                                <td>
                                    <a href="{{ route('product.edit',$product) }}" class="btn btn-primary">
                                        <i class="ri-pencil-line me-1 fs-16 lh-1"></i> Edit
                                    </a>
                                    <a href="{{ route('product.show',$product) }}" class="btn btn-secondary">
                                        <i class="ri-search-eye-line me-1 fs-16 lh-1"></i> View
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</x-layout>