routes/web.php
<?php

use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CrudController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\MeasurementUnitController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductDataController;
use App\Http\Controllers\ProductLedgerController;
use App\Http\Controllers\ProductPurchaseController;
use App\Http\Controllers\StorageController;
use App\Http\Controllers\StorageTypeController;
use App\Http\Controllers\SubmissionController;
use App\Http\Controllers\SubmissionStatusController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TemplateController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('dashboard', DashboardController::class)->name('dashboard');
Route::resource('crud', CrudController::class);

Route::resource('item', ItemController::class);
Route::resource('brand', BrandController::class);
Route::resource('storage', StorageController::class);
Route::resource('storage-type', StorageTypeController::class);
Route::resource('category', CategoryController::class);
Route::resource('supplier', SupplierController::class);
Route::resource('submission-status', SubmissionStatusController::class);
Route::resource('measurement-unit', MeasurementUnitController::class);
Route::resource('product', ProductController::class);
Route::resource('product-purchase', ProductPurchaseController::class);
Route::resource('product-ledger', ProductLedgerController::class);
Route::resource('product-data', ProductDataController::class);
Route::resource('submission', SubmissionController::class);

// Template route
Route::group(['prefix' => 'template', 'as' => 'template.'], function () {
    Route::get('{file}.html', TemplateController::class)->name('dashboard');
});

app/Models/ProductData.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ProductData extends Model
{
    use HasFactory;

    protected $table = 'product_data';

    protected $fillable = ['category_id', 'brand_id', 'item_id', 'about', 'photo', 'status_code'];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function brand()
    {
        return $this->belongsTo(Brand::class);
    }

    public function item()
    {
        return $this->belongsTo(Item::class);
    }

    public static function list()
    {
        $data = self::join('master_items', 'master_items.id', 'item_id')
            ->join('master_brands', 'master_brands.id', 'brand_id')
            ->select('product_data.id', 'master_brands.name AS brand', 'master_items.name AS item');

        return $data;
    }
}

app/Http/Controllers/ProductDataController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProductDataRequest;
use App\Models\Brand;
use App\Models\Category;
use App\Models\Item;
use App\Models\ProductData;
use DB;

class ProductDataController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $product_datas = ProductData::get();

        return view('product_data.index', compact('product_datas'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories = Category::list()->get();
        $brands = Brand::list()->get();
        $items = Item::list()->get();

        return view('product_data.create', compact('categories', 'brands', 'items'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(ProductDataRequest $request)
    {
        $data = $request->validated();

        try {
            DB::beginTransaction();

            ProductData::create($data);

            DB::commit();
            session()->flash('success', 'Product data has been added.');

            return redirect()->route('product-data.index');
        } catch (\Exception $e) {
            DB::rollback();
            session()->flash('error', $e->getMessage());

            return redirect()->back()->withInput();
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(ProductData $productData)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(ProductData $productData)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(ProductDataRequest $request, ProductData $productData)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(ProductData $productData)
    {
        //
    }
}

resources/views/product_data/create.blade.php
<x-layout :title="'Create Product Data'">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('product-data.store') }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="FullName">Kategori</label>
                                <select name="category_id" id="category_id" class="form-control">
                                    <option value="">--Sila Pilih Kategori--</option>
                                    @foreach ($categories as $cat)
                                        <option value="{{$cat->id}}">{{$cat->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="FullName">Jenama</label>
                                <select name="brand_id" id="brand_id" class="form-control">
                                    <option value="">--Sila Pilih Jenama--</option>
                                    @foreach ($brands as $br)
                                        <option value="{{$br->id}}">{{$br->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="FullName">Item</label>
                                <select name="item_id" id="item_id" class="form-control">
                                    <option value="">--Sila Pilih Jenama--</option>
                                    @foreach ($items as $it)
                                        <option value="{{$it->id}}">{{$it->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="FullName">Perihal</label>
                               <input type="text" name="about" id="about" class="form-control">
                            </div>
                        </div>
                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="FullName">Status</label>
                                <select name="status_code" id="status_code" class="form-control">
                                    <option value="1">AKTIF</option>
                                    <option value="0">ARKIB</option>
                                </select>
                            </div>
                        </div>
                        <button class="btn btn-primary" type="submit">
                            <i class="ri-add-box-line me-1 fs-16 lh-1"></i> Create
                        </button>
                        <a href="{{ route('product-data.index') }}" class="btn btn-secondary">
                            <i class="ri-arrow-go-back-line me-1 fs-16 lh-1"></i> Back
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

</x-layout>

resources/views/product_data/index.blade.php
@push('before-styles')
    <!-- Datatables css -->
    <link href="{{ asset('velonicadmin/vendor/datatables.net-bs5/css/dataTables.bootstrap5.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-fixedcolumns-bs5/css/fixedColumns.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-fixedheader-bs5/css/fixedHeader.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-buttons-bs5/css/buttons.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-select-bs5/css/select.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
@endpush
@push('before-scripts')
    <!-- Datatables js -->
    <script src="{{ asset('velonicadmin/vendor/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-bs5/js/dataTables.bootstrap5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-fixedcolumns-bs5/js/fixedColumns.bootstrap5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons-bs5/js/buttons.bootstrap5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-select/js/dataTables.select.min.js') }}"></script>
    <script>
        $('.datatable').DataTable({
            keys: true,
            "language": {
                "paginate": {
                    "previous": "<i class='ri-arrow-left-s-line'>",
                    "next": "<i class='ri-arrow-right-s-line'>"
                }
            },
            "drawCallback": function () {
                $('.dataTables_paginate > .pagination').addClass('pagination-rounded');
            }
        });
    </script>
@endpush

<x-layout :title="'Browse Products Data'">

    <div class="row">
        <div class="col-12">
            <a href="{{ route('product-data.create') }}" class="btn btn-primary mb-3">
                <i class="ri-save-line me-1 fs-16 lh-1"></i> New
            </a>
            <div class="card">
                <div class="card-body">
                    <table class="datatable table table-striped dt-responsive nowrap w-100">
                        <thead>
                            <tr>
                                <th>Product Data Id</th>
                                <th>Category</th>
                                <th>Brand</th>
                                <th>Item</th>
                                <th>Created At</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($product_datas ?? [] as $product)
                            <tr>
                                <td>
                                    {{ $product->id }}
                                </td>
                                <td>
                                    {{ $product->category->name }}
                                </td>
                                <td>
                                    {{ $product->brand->name }}
                                </td>
                                <td>
                                    {{ $product->item->name }}
                                </td>
                                <td>
                                    {{ $product->created_at->format('Y-m-d') }}
                                </td>
                                <td>
                                    <a href="{{ route('product-data.edit',$product) }}" class="btn btn-primary">
                                        <i class="ri-pencil-line me-1 fs-16 lh-1"></i> Edit
                                    </a>
                                    <a href="{{ route('product-data.show',$product) }}" class="btn btn-secondary">
                                        <i class="ri-search-eye-line me-1 fs-16 lh-1"></i> View
                                    </a>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</x-layout>