routes/web.php
<?php

use App\Http\Controllers\BrandController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CrudController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\MeasurementUnitController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\ProductDataController;
use App\Http\Controllers\ProductLedgerController;
use App\Http\Controllers\ProductPurchaseController;
use App\Http\Controllers\StorageController;
use App\Http\Controllers\StorageTypeController;
use App\Http\Controllers\SubmissionController;
use App\Http\Controllers\SubmissionStatusController;
use App\Http\Controllers\SupplierController;
use App\Http\Controllers\TemplateController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('dashboard', DashboardController::class)->name('dashboard');
Route::resource('crud', CrudController::class);

Route::resource('item', ItemController::class);
Route::resource('brand', BrandController::class);
Route::resource('storage', StorageController::class);
Route::resource('storage-type', StorageTypeController::class);
Route::resource('category', CategoryController::class);
Route::resource('supplier', SupplierController::class);
Route::resource('submission-status', SubmissionStatusController::class);
Route::resource('measurement-unit', MeasurementUnitController::class);
Route::resource('product', ProductController::class);
Route::resource('product-purchase', ProductPurchaseController::class);
Route::resource('product-ledger', ProductLedgerController::class);
Route::resource('product-data', ProductDataController::class);
Route::resource('submission', SubmissionController::class);

// Template route
Route::group(['prefix' => 'template', 'as' => 'template.'], function () {
    Route::get('{file}.html', TemplateController::class)->name('dashboard');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $table = 'master_categories';

    protected $fillable = [
        'name',
        'status_code',
    ];

    public static function list()
    {
        $data = self::orderBy('name', 'ASC');

        return $data;
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Support\Facades\DB;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $models = Category::all();
        $data['models'] = $models;

        return view('category.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(CategoryRequest $request)
    {
        $data = $request->validated();

        try {
            DB::beginTransaction();

            Category::create($data);

            DB::commit();
            session()->flash('success', 'Category has been added.');

            return redirect()->back();
        } catch (\Exception $e) {
            DB::rollback();
            session()->flash('error', $e->getMessage());

            return redirect()->back()->withInput();
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(Category $category)
    {
        $data['category'] = $category;

        return view('category.show', $data);

    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Category $category)
    {
        $data['category'] = $category;

        return view('category.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(CategoryRequest $request, Category $category)
    {

        $data = $request->validated();

        try {
            DB::beginTransaction();

            $category->update($data);

            DB::commit();
            session()->flash('success', 'Category has been added.');

            return redirect()->back();
        } catch (\Exception $e) {
            DB::rollback();
            session()->flash('error', $e->getMessage());

            return redirect()->back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Category $category)
    {
        try {
            DB::beginTransaction();

            $category->delete();

            DB::commit();
            session()->flash('success', 'Category has been deleted.');

            return redirect()->back();
        } catch (\Exception $e) {
            DB::rollback();
            session()->flash('error', $e->getMessage());

            return redirect()->back()->withInput();
        }
    }
}

resources/views/category/create.blade.php
<x-layout :title="'Create Dummy CRUD'">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('category.store') }}" method="POST">
                        @csrf
                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="Name">Name</label>
                                <input type="text" value="" id="name" name="name" class="form-control" placeholder="Input Name">
                            </div>
                            <div class="mb-2">
                                <label class="form-label" for="Status Code"> Status Code</label>
                                <input type="number" value="" id="status__code" name="status_code" class="form-control" placeholder="Input Status Code">
                            </div>
                          
                        </div>
                        <button class="btn btn-primary" type="submit">
                            <i class="ri-add-box-line me-1 fs-16 lh-1"></i> Create
                        </button>
                        <a href="{{ route('category.index') }}" class="btn btn-secondary">
                            <i class="ri-arrow-go-back-line me-1 fs-16 lh-1"></i> Back
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

</x-layout>

resources/views/category/edit.blade.php
<x-layout :title="'Edit Dummy CRUD'">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form action="{{ route('category.update', $category) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="mb-2">
                                <label class="form-label" for="Name">Name</label>
                                <input type="text" value="{{$category->name}}" id="name" name="name" class="form-control" placeholder="Input Name">
                            </div>
                            <div class="mb-2">
                                <label class="form-label" for="Status Code"> Status Code</label>
                                <input type="number" value="{{$category->status_code}}" id="status__code" name="status_code" class="form-control" placeholder="Input Status Code">
                            </div>
                        </div>
                        <button class="btn btn-primary" type="submit">
                            <i class="ri-save-line me-1 fs-16 lh-1"></i> Save
                        </button>
                        <a href="{{ route('crud.index') }}" class="btn btn-secondary">
                            <i class="ri-arrow-go-back-line me-1 fs-16 lh-1"></i> Back
                        </a>
                    </form>
                </div>
            </div>
        </div>
    </div>

</x-layout>

resources/views/category/index.blade.php
@push('before-styles')
    <!-- Datatables css -->
    <link href="{{ asset('velonicadmin/vendor/datatables.net-bs5/css/dataTables.bootstrap5.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-responsive-bs5/css/responsive.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-fixedcolumns-bs5/css/fixedColumns.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-fixedheader-bs5/css/fixedHeader.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-buttons-bs5/css/buttons.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
    <link href="{{ asset('velonicadmin/vendor/datatables.net-select-bs5/css/select.bootstrap5.min.css') }}" rel="stylesheet"
        type="text/css" />
@endpush
@push('before-scripts')
    <!-- Datatables js -->
    <script src="{{ asset('velonicadmin/vendor/datatables.net/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-bs5/js/dataTables.bootstrap5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-responsive/js/dataTables.responsive.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-responsive-bs5/js/responsive.bootstrap5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-fixedcolumns-bs5/js/fixedColumns.bootstrap5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons-bs5/js/buttons.bootstrap5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons/js/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-buttons/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-keytable/js/dataTables.keyTable.min.js') }}"></script>
    <script src="{{ asset('velonicadmin/vendor/datatables.net-select/js/dataTables.select.min.js') }}"></script>
    <script>
        $('.datatable').DataTable({
            keys: true,
            "language": {
                "paginate": {
                    "previous": "<i class='ri-arrow-left-s-line'>",
                    "next": "<i class='ri-arrow-right-s-line'>"
                }
            },
            "drawCallback": function () {
                $('.dataTables_paginate > .pagination').addClass('pagination-rounded');
            }
        });
    </script>
@endpush

<x-layout :title="'Browse Category'">

    <div class="row">
        <div class="col-12">
            <a href="{{ route('category.create') }}" class="btn btn-primary mb-3">
                <i class="ri-save-line me-1 fs-16 lh-1"></i> New
            </a>
            <div class="card">
                <div class="card-body">
                    <table class="datatable table table-striped dt-responsive nowrap w-100">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Created At</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($models ?? [] as $model)
                            <tr>
                                <td>
                                    {{ $model->id }}
                                </td>
                                <td>
                                    {{ $model->name }}
                                </td>
                                <td>
                                    {{ $model->created_at->format('Y-m-d') }}
                                </td>
                                <td>
                                    <a href="{{ route('category.edit', $model) }}" class="btn btn-primary">
                                        <i class="ri-pencil-line me-1 fs-16 lh-1"></i> Edit
                                    </a>
                                    <a href="{{ route('category.show', $model) }}" class="btn btn-secondary">
                                        <i class="ri-search-eye-line me-1 fs-16 lh-1"></i> View
                                    </a>
                                    <form action="{{ route('category.destroy', $model)}}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-danger">
                                            <i class="ri-search-eye-line me-1 fs-16 lh-1"></i> Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</x-layout>

resources/views/category/show.blade.php
<x-layout :title="'Show Dummy CRUD'">

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <table class="table table-condensed mb-0 border-top">
                        <tbody>
                            <tr>
                                <th scope="row">Label Text</th>
                                <td>
                                    Input Value
                                </td>
                            </tr>
                            <tr>
                                <th scope="row">Label Text</th>
                                <td>
                                    Input Value
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <a href="{{ route('crud.index') }}" class="btn btn-secondary mt-2">
                        <i class="ri-arrow-go-back-line me-1 fs-16 lh-1"></i> Back
                    </a>
                </div>
            </div>
        </div>
    </div>

</x-layout>